[package]
name = "trill"
version = "0.1.0"
edition = "2021"
description = "A CLI blockchain explorer compatible with EVM-supporting chains."

[dependencies]
clap = { version = "4.5.0", features = ["derive"] }