[package]
name = "trill"
version = "0.1.0"
edition = "2021"
description = "A CLI blockchain explorer compatible with EVM-supporting chains."

[dependencies]
cursive = "0.20.0"
# Flexible concrete Error Reporting type built on std::error::Error with customizable Reports
eyre = "0.6.12"
log = "0.4"
env_logger = "0.9"
